"""LightGBM text model interop.

Every fixture here is a miniature model file written out by hand as a string
literal, small enough that its predictions are worked out on paper in the
comment above it. Nothing is downloaded and nothing is generated by
LightGBM: the point is to pin the format this converter claims to read, so a
fixture that drifts from LightGBM's real output is a bug the test can be
edited to catch rather than a network flake.

`_parse_lgbm_text` strips each line before looking at it, so the fixtures are
indented to sit inside their functions and stay readable.
"""

from std.os import remove
from std.testing import assert_equal, assert_raises, assert_true, TestSuite

from mojoboost.boosting import (
    CUSTOM,
    SQUARED_ERROR,
    Booster,
    BoosterParams,
)
from mojoboost.categorical import CAT_BITSET_WORDS
from mojoboost.lgbm_model_io import (
    dump_lgbm_model,
    dump_lgbm_multiclass_model,
    lgbm_model_file_kind,
    lgbm_objective_code,
    lgbm_objective_name,
    lgbm_text_kind,
    load_lgbm_model,
    parse_lgbm_model,
    parse_lgbm_multiclass_model,
    save_lgbm_model,
)
from mojoboost.model import Model, fit
from mojoboost.tree import Tree, TreeParams

comptime _TMP_PATH = "./.test_lgbm_model_io.tmp"


def _nan() raises -> Float64:
    return Float64(String("nan"))


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


def _regression_text() -> String:
    """Two features, two trees, every value dyadic so the arithmetic below is
    exact.

    Tree 0: internal 0 splits feature 0 at 2.5, its left child is internal 1
    (feature 1 at 4.5) and its right child is leaf 2. Internal 1's children
    are leaf 0 and leaf 1. So

        x0 <= 2.5 and x1 <= 4.5  ->  0.5
        x0 <= 2.5 and x1 >  4.5  -> -0.25
        x0 >  2.5                ->  1.75

    Tree 1 is a stump on feature 1 at 1.5: 0.125 left, -0.0625 right.

        (1, 1) ->  0.5   + 0.125   =  0.625
        (1, 9) -> -0.25  - 0.0625  = -0.3125
        (5, 0) ->  1.75  + 0.125   =  1.875
    """
    return String(
        """tree
        version=v4
        num_class=1
        num_tree_per_iteration=1
        label_index=0
        max_feature_idx=1
        objective=regression
        feature_names=Column_0 Column_1
        feature_infos=[0:10] [0:10]
        tree_sizes=0 0

        Tree=0
        num_leaves=3
        num_cat=0
        split_feature=0 1
        split_gain=10 5
        threshold=2.5 4.5
        decision_type=2 2
        left_child=1 -1
        right_child=-3 -2
        leaf_value=0.5 -0.25 1.75
        leaf_count=3 4 5
        internal_value=0.1 0.2
        internal_count=12 7
        is_linear=0
        shrinkage=1


        Tree=1
        num_leaves=2
        num_cat=0
        split_feature=1
        split_gain=2
        threshold=1.5
        decision_type=2
        left_child=-1
        right_child=-2
        leaf_value=0.125 -0.0625
        leaf_count=6 6
        internal_value=0.0
        internal_count=12
        is_linear=0
        shrinkage=1


        end of trees

        feature_importances:
        Column_1=2
        Column_0=1

        parameters:
        [objective: regression]

        end of parameters

        pandas_categorical:null
        """
    )


def _stump_text(
    decision_type: String,
    threshold: String = "-1",
    header_extra: String = "",
    tree_extra: String = "",
) -> String:
    """One feature, one stump: `x <= threshold` gives 1.0, otherwise -1.0.

    With `threshold=-1` a missing value is separable from a real one: a
    `missing_type=None` node bins NaN as 0.0, which is above -1 and so goes
    right, while a `missing_type=NaN` node routes it by `default_left`
    whatever the threshold says.
    """
    return (
        String(
            """tree
        version=v4
        num_class=1
        num_tree_per_iteration=1
        label_index=0
        max_feature_idx=0
        objective=regression
        feature_names=Column_0
        feature_infos=[-1:-1]
        tree_sizes=0
        """
        )
        + header_extra
        + """
        Tree=0
        num_leaves=2
        num_cat=0
        split_feature=0
        split_gain=1
        threshold="""
        + threshold
        + """
        decision_type="""
        + decision_type
        + """
        left_child=-1
        right_child=-2
        leaf_value=1 -1
        leaf_count=5 5
        internal_value=0
        internal_count=10
        is_linear=0
        shrinkage=1
        """
        + tree_extra
        + """

        end of trees

        pandas_categorical:null
        """
    )


def _multiclass_text() -> String:
    """Two classes, one round: class 0's tree is +1 left / -1 right on
    feature 0 at 0.5, class 1's is the mirror image. So x=0 gives raw
    [1, -1] and x=1 gives raw [-1, 1]."""
    return String(
        """tree
        version=v4
        num_class=2
        num_tree_per_iteration=2
        label_index=0
        max_feature_idx=0
        objective=multiclass num_class:2
        feature_names=Column_0
        feature_infos=[0:1]
        tree_sizes=0 0

        Tree=0
        num_leaves=2
        num_cat=0
        split_feature=0
        split_gain=1
        threshold=0.5
        decision_type=2
        left_child=-1
        right_child=-2
        leaf_value=1 -1
        leaf_count=5 5
        internal_value=0
        internal_count=10
        is_linear=0
        shrinkage=1


        Tree=1
        num_leaves=2
        num_cat=0
        split_feature=0
        split_gain=1
        threshold=0.5
        decision_type=2
        left_child=-1
        right_child=-2
        leaf_value=-1 1
        leaf_count=5 5
        internal_value=0
        internal_count=10
        is_linear=0
        shrinkage=1


        end of trees

        pandas_categorical:null
        """
    )


# ---------------------------------------------------------------------------
# Reading
# ---------------------------------------------------------------------------


def test_reads_two_tree_regression_model() raises:
    var model = parse_lgbm_model(_regression_text())
    assert_equal(model.booster.objective, SQUARED_ERROR)
    assert_equal(model.n_iterations(), 2)
    assert_equal(model.mapper.n_features, 2)

    var a: List[Float64] = [1.0, 1.0]
    var b: List[Float64] = [1.0, 9.0]
    var c: List[Float64] = [5.0, 0.0]
    assert_equal(model.predict(a), 0.625)
    assert_equal(model.predict(b), -0.3125)
    assert_equal(model.predict(c), 1.875)


def test_synthesized_mapper_holds_exactly_the_used_thresholds() raises:
    var model = parse_lgbm_model(_regression_text())
    # Feature 0 is split once (2.5), feature 1 twice (1.5 and 4.5), ascending
    # and deduplicated.
    assert_equal(model.mapper.edge_offsets[0], 0)
    assert_equal(model.mapper.edge_offsets[1], 1)
    assert_equal(model.mapper.edge_offsets[2], 3)
    assert_equal(model.mapper.edges[0], 2.5)
    assert_equal(model.mapper.edges[1], 1.5)
    assert_equal(model.mapper.edges[2], 4.5)
    # No node claims missing_type=NaN, so no feature reserves a missing bin
    # and the widest feature needs three ordinary bins.
    assert_equal(model.mapper.missing_bin[0], -1)
    assert_equal(model.mapper.missing_bin[1], -1)
    assert_equal(model.mapper.n_bins, 3)


def test_node_counts_come_from_leaf_and_internal_count() raises:
    var model = parse_lgbm_model(_regression_text())
    ref tree = model.booster.trees[0]
    assert_true(tree.has_node_counts())
    # Preorder: root, internal 1, leaf 0, leaf 1, then leaf 2.
    assert_equal(tree.count[0], 12.0)
    assert_equal(tree.count[1], 7.0)
    assert_equal(tree.count[2], 3.0)
    assert_equal(tree.count[3], 4.0)
    assert_equal(tree.count[4], 5.0)
    # Parents precede children, which every top-down pass in mojoboost needs.
    assert_equal(tree.left[0], 1)
    assert_equal(tree.right[0], 4)
    assert_equal(tree.n_leaves, 3)


def test_reads_single_leaf_tree() raises:
    var text = String(
        """tree
        version=v4
        num_class=1
        num_tree_per_iteration=1
        label_index=0
        max_feature_idx=0
        objective=regression
        feature_names=Column_0
        feature_infos=none
        tree_sizes=0

        Tree=0
        num_leaves=1
        num_cat=0
        split_feature=
        split_gain=
        threshold=
        decision_type=
        left_child=
        right_child=
        leaf_value=0.375
        leaf_count=10
        internal_value=
        internal_count=
        is_linear=0
        shrinkage=1


        end of trees

        pandas_categorical:null
        """
    )
    var model = parse_lgbm_model(text)
    var row: List[Float64] = [123.0]
    assert_equal(model.predict(row), 0.375)
    assert_equal(model.booster.trees[0].n_leaves, 1)


def test_missing_type_nan_routes_by_default_left() raises:
    # decision_type 10 = default_left | (NaN << 2).
    var model = parse_lgbm_model(_stump_text("10"))
    assert_equal(model.mapper.missing_bin[0], 2)
    var nan_row: List[Float64] = [_nan()]
    var low: List[Float64] = [-5.0]
    var high: List[Float64] = [5.0]
    assert_equal(model.predict(nan_row), 1.0)
    assert_equal(model.predict(low), 1.0)
    assert_equal(model.predict(high), -1.0)


def test_missing_type_nan_routes_by_default_right() raises:
    # decision_type 8 = (NaN << 2), no default_left bit.
    var model = parse_lgbm_model(_stump_text("8"))
    assert_equal(model.mapper.missing_bin[0], 2)
    var nan_row: List[Float64] = [_nan()]
    var low: List[Float64] = [-5.0]
    assert_equal(model.predict(nan_row), -1.0)
    assert_equal(model.predict(low), 1.0)


def test_missing_type_none_bins_nan_as_zero() raises:
    # decision_type 2 = default_left only; missing_type is None, so NaN is
    # binned as the value 0.0 and the threshold (-1) decides, sending it
    # right despite the default.
    var model = parse_lgbm_model(_stump_text("2"))
    assert_equal(model.mapper.missing_bin[0], -1)
    assert_equal(model.mapper.n_bins, 2)
    var nan_row: List[Float64] = [_nan()]
    assert_equal(model.predict(nan_row), -1.0)


def test_reads_multiclass_model() raises:
    var model = parse_lgbm_multiclass_model(_multiclass_text())
    assert_equal(model.booster.n_classes, 2)
    assert_equal(model.n_iterations(), 1)

    var left: List[Float64] = [0.0]
    var right: List[Float64] = [1.0]
    var raw_left = model.predict_raw(left)
    assert_equal(raw_left[0], 1.0)
    assert_equal(raw_left[1], -1.0)
    assert_equal(model.predict_class(left), 0)
    assert_equal(model.predict_class(right), 1)

    var proba = model.predict_proba(left)
    assert_true(proba[0] > proba[1])
    assert_true(abs(proba[0] + proba[1] - 1.0) < 1e-12)


def test_kind_dispatch_and_cross_loader_errors() raises:
    assert_equal(lgbm_text_kind(_regression_text()), "objective")
    assert_equal(lgbm_text_kind(_multiclass_text()), "multiclass")
    with assert_raises():
        _ = parse_lgbm_model(_multiclass_text())
    with assert_raises():
        _ = parse_lgbm_multiclass_model(_regression_text())


def test_file_roundtrip_on_disk() raises:
    var model = parse_lgbm_model(_regression_text())
    save_lgbm_model(model, _TMP_PATH)
    assert_equal(lgbm_model_file_kind(_TMP_PATH), "objective")
    var loaded = load_lgbm_model(_TMP_PATH)
    var row: List[Float64] = [1.0, 9.0]
    assert_equal(loaded.predict(row), model.predict(row))
    remove(_TMP_PATH)


# ---------------------------------------------------------------------------
# Rejections
# ---------------------------------------------------------------------------


def test_rejects_categorical_decision_type() raises:
    # decision_type bit 0 marks a categorical split.
    with assert_raises():
        _ = parse_lgbm_model(_stump_text("1"))


def test_rejects_num_cat() raises:
    with assert_raises():
        _ = parse_lgbm_model(
            _stump_text("2", tree_extra="        num_cat=1\n")
        )


def test_rejects_missing_type_zero() raises:
    # decision_type 4 = (Zero << 2): a zero feature value counts as missing,
    # which a bin-routed tree cannot express.
    with assert_raises():
        _ = parse_lgbm_model(_stump_text("4"))


def test_rejects_linear_tree() raises:
    with assert_raises():
        _ = parse_lgbm_model(
            _stump_text("2", tree_extra="        is_linear=1\n")
        )


def test_rejects_leaf_coefficients() raises:
    with assert_raises():
        _ = parse_lgbm_model(
            _stump_text("2", tree_extra="        leaf_coeff=0.5 0.25\n")
        )


def test_rejects_averaged_output() raises:
    with assert_raises():
        _ = parse_lgbm_model(
            _stump_text("2", header_extra="        average_output\n")
        )


def test_rejects_mixed_missing_type_on_one_feature() raises:
    # Two nodes on feature 0 disagreeing about missing_type (2 vs 10);
    # mojoboost reserves a missing bin per feature, so they must agree.
    var text = String(
        """tree
        version=v4
        num_class=1
        num_tree_per_iteration=1
        label_index=0
        max_feature_idx=0
        objective=regression
        feature_names=Column_0
        feature_infos=[0:1]
        tree_sizes=0

        Tree=0
        num_leaves=3
        num_cat=0
        split_feature=0 0
        split_gain=1 1
        threshold=0.5 0.25
        decision_type=2 10
        left_child=1 -1
        right_child=-3 -2
        leaf_value=1 -1 2
        leaf_count=3 3 4
        internal_value=0 0
        internal_count=10 6
        is_linear=0
        shrinkage=1


        end of trees

        pandas_categorical:null
        """
    )
    with assert_raises():
        _ = parse_lgbm_model(text)


def test_rejects_malformed_child_links() raises:
    # num_leaves=2 but both children point at leaf 0, so leaf 1 is orphaned
    # and leaf 0 is reached twice.
    var text = _stump_text("2")
    var broken = String("")
    for raw_line in text.split("\n"):
        var line = String(String(raw_line).strip())
        if line == "right_child=-2":
            broken += "right_child=-1\n"
        else:
            broken += line + "\n"
    with assert_raises():
        _ = parse_lgbm_model(broken)


def test_rejects_out_of_range_feature() raises:
    var text = _stump_text("2")
    var broken = String("")
    for raw_line in text.split("\n"):
        var line = String(String(raw_line).strip())
        if line == "split_feature=0":
            broken += "split_feature=7\n"
        else:
            broken += line + "\n"
    with assert_raises():
        _ = parse_lgbm_model(broken)


def test_rejects_unsupported_version() raises:
    var text = _stump_text("2")
    var broken = String("")
    for raw_line in text.split("\n"):
        var line = String(String(raw_line).strip())
        if line == "version=v4":
            broken += "version=v9\n"
        else:
            broken += line + "\n"
    with assert_raises():
        _ = parse_lgbm_model(broken)


def test_rejects_text_that_is_not_a_lgbm_model() raises:
    with assert_raises():
        _ = parse_lgbm_model(String("mojoboost v3\nobjective 0\n"))


def test_objective_mapping_and_its_rejections() raises:
    assert_equal(lgbm_objective_code(String("regression")), SQUARED_ERROR)
    assert_equal(lgbm_objective_code(String("binary sigmoid:1")), 1)
    # A non-unit sigmoid would change every probability.
    with assert_raises():
        _ = lgbm_objective_code(String("binary sigmoid:2"))
    # One binary model per class is not a softmax.
    with assert_raises():
        _ = lgbm_objective_code(String("multiclassova num_class:3"))
    # An empty objective line means the model was trained with a callback.
    with assert_raises():
        _ = lgbm_objective_code(String(""))
    with assert_raises():
        _ = lgbm_objective_code(String("not_an_objective"))


# ---------------------------------------------------------------------------
# Writing
# ---------------------------------------------------------------------------


def test_rejects_writing_a_custom_objective() raises:
    with assert_raises():
        _ = lgbm_objective_name(CUSTOM)


def _one_split_tree(
    threshold_bin: Int, var cat_offset: List[Int], var cat_bitset: List[UInt64]
) raises -> Tree:
    """A hand-built three-node tree, used to drive the writer's rejections."""
    var feature: List[Int] = [0, -1, -1]
    var bins: List[Int] = [threshold_bin, -1, -1]
    var left: List[Int] = [1, -1, -1]
    var right: List[Int] = [2, -1, -1]
    var value: List[Float64] = [0.0, 1.0, -1.0]
    var gain: List[Float64] = [1.0, 0.0, 0.0]
    var default_left: List[Bool] = [False, False, False]
    var missing_bin: List[Int] = [-1, -1, -1]
    var count: List[Float64] = [10.0, 5.0, 5.0]
    return Tree(
        feature^,
        bins^,
        left^,
        right^,
        value^,
        gain^,
        2,
        default_left^,
        missing_bin^,
        cat_offset^,
        cat_bitset^,
        count^,
    )


def test_rejects_writing_a_categorical_node() raises:
    var base = parse_lgbm_model(_stump_text("2"))
    var bitset = List[UInt64]()
    for _ in range(CAT_BITSET_WORDS):
        bitset.append(0)
    var cat_offset: List[Int] = [0, -1, -1]
    var trees = List[Tree]()
    trees.append(_one_split_tree(-1, cat_offset^, bitset^))
    var model = Model(
        base.mapper.copy(), Booster(trees^, 0.0, 1.0, SQUARED_ERROR)
    )
    with assert_raises():
        _ = dump_lgbm_model(model)


def test_rejects_writing_a_bin_with_no_edge() raises:
    # The stump's feature has exactly one edge, so bin 7 has no upper bound
    # and therefore no real-valued LightGBM threshold.
    var base = parse_lgbm_model(_stump_text("2"))
    var trees = List[Tree]()
    trees.append(_one_split_tree(7, List[Int](), List[UInt64]()))
    var model = Model(
        base.mapper.copy(), Booster(trees^, 0.0, 1.0, SQUARED_ERROR)
    )
    with assert_raises():
        _ = dump_lgbm_model(model)


def test_written_text_is_stable_under_reparsing() raises:
    # The first dump folds the learning rate and base score into the leaf
    # values, so it is not the input text. From then on the conversion is a
    # fixed point: parsing and re-dumping must reproduce it byte for byte.
    var once = dump_lgbm_model(parse_lgbm_model(_regression_text()))
    var twice = dump_lgbm_model(parse_lgbm_model(once))
    assert_equal(once, twice)


def test_written_multiclass_text_is_stable_under_reparsing() raises:
    var once = dump_lgbm_multiclass_model(
        parse_lgbm_multiclass_model(_multiclass_text())
    )
    var twice = dump_lgbm_multiclass_model(
        parse_lgbm_multiclass_model(once)
    )
    assert_equal(once, twice)


def test_written_model_predicts_identically() raises:
    var model = parse_lgbm_model(_regression_text())
    var back = parse_lgbm_model(dump_lgbm_model(model))
    var rows: List[Float64] = [
        1.0, 1.0, 1.0, 9.0, 5.0, 0.0, 2.5, 4.5, -3.0, 100.0,
    ]
    for i in range(len(rows) // 2):
        var row: List[Float64] = [rows[2 * i], rows[2 * i + 1]]
        assert_equal(back.predict(row), model.predict(row))


# ---------------------------------------------------------------------------
# Round trip through a trained model
# ---------------------------------------------------------------------------


def _make_dataset(
    n_rows: Int, mut features: List[Float64], mut target: List[Float64]
) raises:
    """Two features, the first carrying missing values so the round trip has
    to preserve missing routing, not just thresholds."""
    var nan = _nan()
    var state: UInt64 = 42
    for r in range(n_rows):
        state = state * 6364136223846793005 + 1442695040888963407
        var v = Float64(state >> 11) * (1.0 / 9007199254740992.0)
        features.append(nan if r % 7 == 0 else v)
    for _ in range(n_rows):
        state = state * 6364136223846793005 + 1442695040888963407
        features.append(Float64(state >> 11) * (1.0 / 9007199254740992.0))
    for r in range(n_rows):
        var x0 = features[r]
        var x1 = features[n_rows + r]
        target.append(3.0 * x1 + (0.0 if r % 7 == 0 else 2.0 * x0 * x1))


def test_trained_model_survives_the_round_trip_bit_exactly() raises:
    var n_rows = 240
    var features = List[Float64]()
    var target = List[Float64]()
    _make_dataset(n_rows, features, target)

    var params = BoosterParams(12, 0.1, TreeParams(8, 5, 1.0, 1e-3))
    var model = fit(
        features, n_rows, 2, target, SQUARED_ERROR, params, 32
    )
    # The base score is the label mean here, and the learning rate is 0.1, so
    # this exercises the fold-into-tree-0 path rather than a trivial one.
    assert_true(model.booster.base_score != 0.0)
    assert_equal(model.booster.learning_rate, 0.1)
    assert_true(model.mapper.missing_bin[0] >= 0)

    var back = parse_lgbm_model(dump_lgbm_model(model))
    assert_equal(back.booster.learning_rate, 1.0)
    assert_equal(back.booster.base_score, 0.0)
    assert_equal(back.n_iterations(), model.n_iterations())

    for r in range(n_rows):
        var row: List[Float64] = [features[r], features[n_rows + r]]
        assert_equal(back.predict(row), model.predict(row))

    # Values the model never saw, including a missing first feature, which
    # only routes the same way if the reserved missing bin survived.
    var unseen: List[Float64] = [_nan(), 0.5]
    assert_equal(back.predict(unseen), model.predict(unseen))
    var extreme: List[Float64] = [1e300, -1e300]
    assert_equal(back.predict(extreme), model.predict(extreme))


def main() raises:
    TestSuite.discover_tests[__functions_in_module()]().run()
