#!/usr/bin/env python3
"""Check and record the model format fixture set.

    python3 tools/model_fixture_manifest.py --check   # verify everything
    python3 tools/model_fixture_manifest.py --write   # record checksums

A fixture is a model file an older format version wrote, kept so a newer
build can prove it still reads it. The promise is section 7.2 of
`docs/COMPATIBILITY_POLICY.md`: a release reads every model file any
earlier release wrote. `compatibility/fixtures/README.md` says what a
fixture is and where one may come from, and
`compatibility/MODEL_FORMAT_MIGRATIONS.md` is normative for the per
version rules.

The register is in two halves, because `tomllib` reads TOML and the
standard library cannot write it.

- `compatibility/fixtures/manifest.toml` is hand-maintained. It declares
  which fixtures must exist, what each is, and where it came from.
- `compatibility/fixtures/checksums.json` is generated by `--write`. It
  records the size and SHA-256 of each of a fixture's three files.

This tool never writes, moves, or regenerates a fixture. **A fixture is
never regenerated**: it is evidence about what a build wrote at a moment,
and regenerating it destroys the only thing it proves. When a fixture
stops loading, the reader is broken, and the fix goes in the reader.
`--write` touches `checksums.json` and nothing else, and it refuses to
overwrite a checksum that already exists unless `--accept-new` says so.

Constraints, the same three as `tools/api_snapshot.py` and
`tools/check_parity.py`. Standard library only, builds nothing and imports
no part of mojotrees, deterministic output.

Shared implementation
---------------------
The model format version constants are parsed by
`api_snapshot.model_format_block`, imported from the sibling module rather
than reimplemented. Two parsers of `src/mojotrees/serialize.mojo` would
drift, and the whole point of check F1 below is that the versions in this
repository already disagree with each other in three places.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import tomllib
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from api_snapshot import (  # noqa: E402  (after the path insert, by design)
    ROOT,
    Deriver,
    model_format_block,
    rel,
)

FIXTURES = ROOT / "compatibility" / "fixtures"
MANIFEST = FIXTURES / "manifest.toml"
CHECKSUMS = FIXTURES / "checksums.json"

CHECKSUM_SCHEMA_VERSION = 1

# Provenance kinds and the fields each requires. The three are not
# interchangeable: `released` is evidence about a file a user could hold,
# `built_at_commit` is reproducible if the commit still builds, and
# `synthetic` proves only that the reader handles the format as specified.
PROVENANCE_REQUIRED = {
    "released": ("release", "platform", "produced_at"),
    "built_at_commit": ("commit", "toolchain", "platform", "produced_at"),
    "synthetic": ("authored_from", "authored_by", "produced_at"),
}

# Stem prefixes that .gitignore swallows at any depth. A fixture matching
# one of these would be produced, would pass every local check, and would
# never land in a commit, which is the failure mode most likely to go
# unnoticed. `/*.mbst` is root-anchored and does not reach this directory.
IGNORED_PREFIXES = ("capi_test_", ".test_")


def sha256_of(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as fp:
        for chunk in iter(lambda: fp.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def load_manifest(d: Deriver):
    try:
        return tomllib.loads(MANIFEST.read_text())
    except OSError as exc:
        d.problem(f"cannot read {rel(MANIFEST)}: {exc}")
    except tomllib.TOMLDecodeError as exc:
        d.problem(f"{rel(MANIFEST)} is not valid TOML: {exc}")
    return None


def load_checksums(d: Deriver):
    if not CHECKSUMS.exists():
        return None
    try:
        return json.loads(CHECKSUMS.read_text())
    except json.JSONDecodeError as exc:
        d.problem(f"{rel(CHECKSUMS)} is not valid JSON: {exc}")
        return None


def files_of(row: dict, suffixes: dict) -> dict:
    """The three paths a fixture's stem resolves to, keyed by role."""
    stem = row.get("stem") or ""
    return {
        role: FIXTURES / f"{stem}{suffix}"
        for role, suffix in sorted(suffixes.items())
    }


def check_declarations(manifest: dict, d: Deriver) -> list:
    """Everything about the register that can be checked without the files
    existing. Runs first so that a malformed row is reported even on a
    tree where no fixture has been produced yet."""
    rows = manifest.get("fixture", [])
    if not rows:
        d.problem(f"{rel(MANIFEST)} declares no fixtures")
        return []

    seen_ids, seen_stems = set(), set()
    known = set(manifest.get("known_facts", []))
    for row in rows:
        fid = row.get("id")
        if not fid:
            d.problem("a fixture row has no id")
            continue
        if fid in seen_ids:
            d.problem(f"duplicate fixture id {fid!r}")
        seen_ids.add(fid)

        stem = row.get("stem")
        if not stem:
            d.problem(f"{fid}: no stem")
        elif stem in seen_stems:
            d.problem(f"{fid}: stem {stem!r} is already used")
        else:
            seen_stems.add(stem)
            leaf = stem.rsplit("/", 1)[-1]
            for prefix in IGNORED_PREFIXES:
                if leaf.startswith(prefix):
                    d.problem(
                        f"{fid}: stem {stem!r} starts with {prefix!r}, which "
                        f".gitignore swallows at any depth; the fixture would "
                        f"never land in a commit"
                    )

        for fact in row.get("carries", []):
            if known and fact not in known:
                d.problem(
                    f"{fid}: carries {fact!r}, which is not in known_facts"
                )

        prov = row.get("provenance") or {}
        kind = prov.get("kind")
        if kind not in PROVENANCE_REQUIRED:
            d.problem(
                f"{fid}: provenance.kind is {kind!r}; expected one of "
                + ", ".join(sorted(PROVENANCE_REQUIRED))
            )
        else:
            for field in PROVENANCE_REQUIRED[kind]:
                if not prov.get(field):
                    d.problem(
                        f"{fid}: provenance.kind is {kind!r} and requires "
                        f"{field!r}, which is empty or absent"
                    )
        parent = prov.get("derived_from")
        if parent and parent not in {r.get("id") for r in rows}:
            d.problem(
                f"{fid}: provenance.derived_from names {parent!r}, which is "
                f"not a fixture in this manifest"
            )
    return rows


def check_coverage(rows: list, d: Deriver) -> None:
    """Every model format version this build can read needs a fixture, and
    the version it writes needs one most of all.

    The readable set comes from `api_snapshot.model_format_block`, which
    parses the `if token == "vN"` chain in serialize.mojo. Deriving it
    rather than listing it here is what makes a new format version fail
    this check on the commit that adds it, instead of on the release that
    ships it.
    """
    fmt = model_format_block(d)
    readable = fmt.get("readable") or []
    writer = fmt.get("writer")
    if not readable:
        d.note("readable version set could not be derived; coverage unchecked")
        return

    covered: dict = {}
    for row in rows:
        version = row.get("model_format_version")
        covered.setdefault(version, []).append(row.get("id"))

    for version in readable:
        if version not in covered:
            d.problem(
                f"the reader accepts v{version} and no fixture covers it; "
                f"see compatibility/MODEL_FORMAT_MIGRATIONS.md section 4"
            )
    if writer is not None and writer not in covered:
        d.problem(
            f"the writer emits v{writer} and no fixture covers it; a format "
            f"the build writes and nothing pins is the one most likely to "
            f"change without anyone noticing"
        )
    for version in sorted(covered):
        if version not in readable:
            d.problem(
                f"fixtures {covered[version]} declare v{version}, which the "
                f"reader does not accept"
            )

    kinds = {row.get("kind") for row in rows}
    for kind in ("objective", "multiclass"):
        if kind not in kinds:
            d.problem(
                f"no fixture declares kind {kind!r}; the kind token is what "
                f"a reader dispatches on from the header alone"
            )


def compute(rows: list, suffixes: dict, d: Deriver) -> dict:
    """Size and SHA-256 for every file of every fixture that exists."""
    out: dict = {}
    for row in rows:
        fid = row.get("id")
        if not fid:
            continue
        entry = {}
        for role, path in files_of(row, suffixes).items():
            if not path.is_file():
                d.problem(f"{fid}: {rel(path)} does not exist")
                continue
            if path.stat().st_size == 0:
                d.problem(f"{fid}: {rel(path)} is empty")
                continue
            entry[role] = {
                "size_bytes": path.stat().st_size,
                "sha256": sha256_of(path),
            }
        if entry:
            out[fid] = entry
    return out


def compare(recorded: dict, computed: dict, d: Deriver) -> None:
    """A checksum mismatch is the loudest failure this tool has, and the
    message says what it means: a fixture changed, and a fixture is not
    allowed to change."""
    for fid in sorted(set(recorded) | set(computed)):
        was, now = recorded.get(fid, {}), computed.get(fid, {})
        if fid not in computed:
            d.problem(
                f"{fid}: recorded in {rel(CHECKSUMS)} and its files are "
                f"missing. A fixture is evidence; deleting one destroys what "
                f"it proved"
            )
            continue
        if fid not in recorded:
            d.problem(
                f"{fid}: present on disk and absent from {rel(CHECKSUMS)}; "
                f"run --write"
            )
            continue
        for role in sorted(set(was) | set(now)):
            old, new = was.get(role), now.get(role)
            if old is None:
                d.problem(f"{fid}.{role}: not recorded; run --write")
            elif new is None:
                d.problem(f"{fid}.{role}: recorded and missing on disk")
            elif old.get("sha256") != new.get("sha256"):
                d.problem(
                    f"{fid}.{role}: CHECKSUM MISMATCH. Recorded "
                    f"{old.get('sha256')}, on disk {new.get('sha256')}. A "
                    f"fixture is never regenerated. If a reader change made "
                    f"this file wrong, fix the reader; if the fixture itself "
                    f"was wrong, retire the row and add a new one with its "
                    f"own id, so the history stays legible"
                )
            elif old.get("size_bytes") != new.get("size_bytes"):
                d.problem(
                    f"{fid}.{role}: size changed with the digest unchanged, "
                    f"which should be impossible; suspect the manifest"
                )


def dump_checksums(computed: dict, rows: list) -> None:
    payload = {
        "schema_version": CHECKSUM_SCHEMA_VERSION,
        "generated_by": "tools/model_fixture_manifest.py",
        "note": (
            "Computed half of the fixture register. The declared half is "
            "manifest.toml. A fixture is never regenerated; a change to any "
            "digest here is a failure, not an update."
        ),
        "fixtures": computed,
        "declared_but_absent": sorted(
            row["id"]
            for row in rows
            if row.get("id") and row["id"] not in computed
        ),
    }
    CHECKSUMS.parent.mkdir(parents=True, exist_ok=True)
    with CHECKSUMS.open("w") as fp:
        json.dump(payload, fp, indent=2, sort_keys=True)
        fp.write("\n")


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        description="Check or record the model format fixture set."
    )
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    parser.add_argument(
        "--accept-new",
        action="store_true",
        help="allow --write to record a digest that differs from one "
        "already in checksums.json. Without it, --write refuses, because a "
        "changed fixture is a failure and not an update",
    )
    args = parser.parse_args(argv)

    d = Deriver()
    manifest = load_manifest(d)
    if manifest is None:
        for problem in d.problems:
            print(f"  PROBLEM: {problem}")
        return 1

    suffixes = manifest.get("suffixes") or {
        "model": ".mbst",
        "input": ".input.tsv",
        "expected": ".expected.tsv",
    }
    rows = check_declarations(manifest, d)
    check_coverage(rows, d)
    computed = compute(rows, suffixes, d)
    recorded_doc = load_checksums(d)
    recorded = (recorded_doc or {}).get("fixtures", {})

    if args.write:
        if recorded and not args.accept_new:
            clashes = []
            for fid, entry in computed.items():
                for role, value in entry.items():
                    was = recorded.get(fid, {}).get(role)
                    if was and was.get("sha256") != value.get("sha256"):
                        clashes.append(f"{fid}.{role}")
            if clashes:
                print(
                    "refusing to overwrite recorded digests for: "
                    + ", ".join(sorted(clashes))
                )
                print(
                    "  A fixture is never regenerated. Pass --accept-new "
                    "only if you are deliberately retiring the recorded "
                    "value and can say why in the release notes."
                )
                return 1
        dump_checksums(computed, rows)
        print(f"wrote {rel(CHECKSUMS)}: {len(computed)} fixture(s) recorded")
        absent = [
            row["id"]
            for row in rows
            if row.get("id") and row["id"] not in computed
        ]
        if absent:
            print(f"  declared and absent: {', '.join(sorted(absent))}")
    else:
        if recorded_doc is None:
            d.problem(
                f"{rel(CHECKSUMS)} does not exist. Produce the fixture files "
                f"named in compatibility/fixtures/README.md, then run "
                f"--write. Until then this check fails, which is the correct "
                f"state: a manifest that passed while the evidence was "
                f"missing would be worth nothing"
            )
        else:
            compare(recorded, computed, d)

    for note in d.notes:
        print(f"  note: {note}")
    for problem in d.problems:
        print(f"  PROBLEM: {problem}")
    if d.problems:
        print(f"\n{len(d.problems)} problem(s)")
        return 1
    print("  ok")
    return 0


if __name__ == "__main__":
    sys.exit(main())
