#!/usr/bin/env python3
"""Generate `docs/PORTING.md` from `mojotrees.port`, and check it is fresh.

    python3 tools/port_report.py --write   # regenerate the page in place
    python3 tools/port_report.py --check   # exit 0 if the page matches
    python3 tools/port_report.py --print   # the page, to stdout

The page and the report a user gets from `print(port(params))` come out of
one `PortReport.render()`. That is the whole point of this script existing
rather than the page being written by hand. A hand-written page is a second
copy of the alias table, of LightGBM's stock defaults and of every refusal
reason, and this repository has already had a default sit wrong in three
places at once because three copies existed and one gate covered none of
them.

Standard library only, and nothing here builds or imports the extension.
`python/mojotrees/port.py` is loaded **by path**, not as `mojotrees.port`,
so importing the package (and therefore `_mojotrees.so`) never happens. That
keeps this runnable on a bare checkout and in CPU-only CI, which is the rule
every gate under `tools/` follows. `port.py` imports nothing from its own
package at module level, which is what makes that possible; if that ever
stops being true this script stops working, and it says so rather than
importing the world.

The three example dicts below are hand-picked. What is generated is their
CLASSIFICATION, every default in every table, and every reason: nothing on
the page is transcribed from a vendor's documentation or from memory. The
dicts are chosen only to make all four categories appear on the page at
once, which an empty dict cannot do.

Exit status is 0 when the mode succeeded and 1 otherwise.
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PORT_MODULE = ROOT / "python" / "mojotrees" / "port.py"
PAGE = ROOT / "docs" / "PORTING.md"

#: One dict per source, chosen so that every category is populated on the
#: page. Each key is a real spelling of that vendor's, and each is either an
#: alias in our own `_resolve_alias` table or a row of
#: `docs/LIGHTGBM_PARITY.md` section 7, so nothing here is invented either.
EXAMPLES = {
    "lightgbm": {
        "num_leaves": 63,
        "learning_rate": 0.05,
        "num_iterations": 500,
        "min_sum_hessian_in_leaf": 0.01,
        "feature_pre_filter": True,
        "forcedsplits_filename": "splits.json",
        "label": "y",
    },
    "xgboost": {
        "eta": 0.05,
        "max_depth": 8,
        "reg_lambda": 2.0,
        "colsample_bytree": 0.8,
        "alpha": 1.0,
        "tree_method": "hist",
    },
    "catboost": {
        "iterations": 500,
        "depth": 8,
        "l2_leaf_reg": 3.0,
        "one_hot_max_size": 10,
        "bootstrap_type": "MVS",
        "nan_mode": "Min",
    },
}

PREAMBLE = """# Porting a LightGBM, XGBoost, or CatBoost configuration

**Generated by `python3 tools/port_report.py --write`. Do not edit by
hand.** Every table below comes out of `mojotrees.port`, through the same
`PortReport.render()` that prints in a console, so this page and that call
cannot disagree.

    from mojotrees import port

    report = port(my_params, source="lightgbm")
    print(report)                        # the tables below, for your dict
    model = MojoTreesRegressor(**report.params)

`port()` sorts every key you passed into four categories.

| category | what it means |
|---|---|
| `honored` | ours under the same name, and the value is used as you gave it |
| `aliased_to` | a vendor spelling of one of our canonical names; the report gives both names |
| `defaulted_differently` | we accept it, you did not name it, and our default is not that vendor's, so your model will differ from theirs unless you set it |
| `refused` | we do not implement it, with the reason this repository already states for it |

A fifth list, `unsourced`, is not a category. It is every fact the report
wanted and could not read. An answer that cannot be sourced appears there
as an absence rather than being guessed at, which is why some rows below
say `unknown` instead of a number.

Where the facts come from is in the module docstring of
`python/mojotrees/port.py`. In short, the alias table is derived from the
`_resolve_alias` call sites that `tools/api_snapshot.py` also reads,
LightGBM's stock defaults and our declared departures from them come from
`tools/check_parity.py`, XGBoost's and CatBoost's resolved defaults come
from the tables in `bench/real_data/scenarios.py` that record the library
call each was read back from, and refusal reasons come from section 7 of
`docs/LIGHTGBM_PARITY.md`.

Two notes on reading the pages below.

- `defaulted_differently` is computed for a caller who set **nothing**, and
  then again for the worked example. A parameter you name yourself leaves
  that list, because you have already decided it.
- `declared` in that table says whether the departure is registered in
  `STOCK_DIVERGENCES` in `tools/check_parity.py` with a reason and an exit
  condition. A `yes` is an argument on the page. A `no` means only that this
  repository records the vendor's value and not a reason for the gap.
"""

ALIAS_INTRO = """## Every vendor spelling we accept

Derived from the `self._resolve_alias(primary, alias, default)` call sites
in `_Base`, which is the same derivation that produces the
`parameter_aliases` block of `compatibility/api_snapshot.json`. `we call it`
is the name the value is sent under, and `default when neither is set` is
the third argument of the call site, which is `unknown` where the call site
computes it rather than spelling it out.
"""


def load_port():
    """`python/mojotrees/port.py` as a module, loaded by path.

    By path and not by import, so nothing here imports `mojotrees` and
    therefore nothing here needs a built extension.
    """
    spec = importlib.util.spec_from_file_location(
        "_mojotrees_port_for_docs", PORT_MODULE
    )
    if spec is None or spec.loader is None:
        raise SystemExit("cannot load %s" % PORT_MODULE)
    module = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(module)
    except ImportError as exc:
        raise SystemExit(
            "python/mojotrees/port.py no longer imports on its own (%s). It "
            "must import nothing from its package at module level, or this "
            "page cannot be generated without a built extension." % exc
        )
    return module


def alias_table(port):
    facts = port._estimator_facts()
    aliases = facts["aliases"]
    if not aliases:
        return "The alias table could not be derived from `sklearn.py`.\n"
    rows = []
    for alias in sorted(aliases):
        entry = aliases[alias]
        rows.append(
            [
                "`%s`" % alias,
                "`%s`" % entry["canonical"],
                port._show(entry["fallback_default"]),
                str(entry["sites"]),
            ]
        )
    return port._table(
        [
            "you pass",
            "we call it",
            "default when neither is set",
            "call sites",
        ],
        rows,
    )


def build(port):
    parts = [
        PREAMBLE.rstrip(),
        "",
        ALIAS_INTRO.rstrip(),
        "",
        alias_table(port),
    ]
    for source in port.SOURCES:
        parts += [
            "",
            "## %s" % source,
            "",
            "### If you set nothing",
            "",
            "What changes for a caller who ports a %s script and names no "
            "hyperparameter at all." % source,
            "",
            port.port({}, source=source)
            .render(heading="an empty dict")
            .rstrip(),
            "",
            "### A worked example",
            "",
            "```python",
            "port(%s," % _pretty(EXAMPLES[source]),
            "     source=%r)" % source,
            "```",
            "",
            port.port(EXAMPLES[source], source=source)
            .render(heading="that dict")
            .rstrip(),
        ]
    return "\n".join(parts).rstrip() + "\n"


def _pretty(mapping):
    items = ", ".join(
        "%r: %r" % (key, value) for key, value in mapping.items()
    )
    return "{" + items + "}"


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--print", dest="to_stdout", action="store_true")
    args = parser.parse_args(argv)

    port = load_port()
    text = build(port)

    if args.to_stdout:
        sys.stdout.write(text)
        return 0
    if args.write:
        PAGE.parent.mkdir(parents=True, exist_ok=True)
        PAGE.write_text(text, encoding="utf-8")
        print("wrote %s (%d lines)" % (PAGE.relative_to(ROOT),
                                       text.count("\n")))
        return 0
    if not PAGE.exists():
        print(
            "%s does not exist; run tools/port_report.py --write"
            % PAGE.relative_to(ROOT)
        )
        return 1
    current = PAGE.read_text(encoding="utf-8")
    if current == text:
        print("%s is up to date" % PAGE.relative_to(ROOT))
        return 0
    print(
        "%s is stale. Something it reports changed -- an alias, a default, a "
        "refusal reason -- and the page still says the old thing. Regenerate "
        "it with `python3 tools/port_report.py --write` in the same commit "
        "as the change." % PAGE.relative_to(ROOT)
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
